name: Print OS Details

# When will it run
on:
  push:
  workflow_dispatch:   # allows manual run from GitHub

jobs:
  os-info-job:
    runs-on: ubuntu-latest   # GitHub runner OS

    steps:
      - name: Print OS name
        run: uname -a

      - name: Print system info
        run: |
          echo "Operating System:"
          cat /etc/os-release

      - name: Print CPU info
        run: lscpu

      - name: Print memory info
        run: free -h

      - name: Print disk info
        run: df -h
