name: my-first-workflow

on: workflow_dispatch
jobs:
  # my-first-jobs:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: List all files
  #       run: ls -la
  #     - name: Print working directory
  #       run: pwd
  #     - name: CheckOut Repo
  #       uses: actions/checkout@v6
  #     - name: List all files
  #       run: ls -la
  my-first-jobs:
    runs-on: ubuntu-latest
    steps:
      - name: Check expressions
        run: echo ${{toJson(github)}}
